import { describe, expect, it } from 'vitest'
import { generatedExercises } from './exercises-generated'
import details from './exercise-details-generated.json'
import illustrations from './images-generated.json'
import videos from './exercise-videos.json'
import { wgerExercises } from './exercises-wger-generated'
import wgerText from './exercise-wger-text.json'
import { exercisePhotoFrames } from '../lib/images'

/** What is actually on disk, resolved by Vite rather than by reading the filesystem. */
const onDisk = new Set(
  Object.keys(import.meta.glob('../../public/repdb/*.webp')).map((p) => `/repdb/${p.split('/').pop()}`),
)

/**
 * The catalogue is generated by `scripts/import-exercises.mjs` from two
 * upstream datasets that move independently of us. These are the invariants a
 * re-import must not break — most of all the ids, which are written into every
 * logged workout and cannot be renamed without losing somebody's history.
 */
describe('generated exercise catalogue', () => {
  it('has no duplicate ids', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    expect(ids.size).toBe(generatedExercises.length)
  })

  it('keeps the free-exercise-db ids the plan generator hardcodes', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    for (const id of ['Barbell_Bench_Press_-_Medium_Grip', 'Barbell_Full_Squat', 'Pullups', 'Plank']) {
      expect(ids, id).toContain(id)
    }
  })

  it('carries both sources', () => {
    const photos = generatedExercises.filter((e) => e.image?.includes('free-exercise-db'))
    const illustrated = generatedExercises.filter((e) => e.image?.startsWith('/repdb/'))
    expect(photos.length).toBeGreaterThan(800)
    expect(illustrated.length).toBeGreaterThan(400)
  })

  it('classifies every movement', () => {
    expect(generatedExercises.filter((e) => !e.category)).toHaveLength(0)
  })

  it('ships every bundled illustration it points at', () => {
    const referenced = [
      ...generatedExercises.map((e) => e.image),
      ...Object.values(illustrations as Record<string, string>),
    ].filter((src): src is string => !!src && src.startsWith('/repdb/'))
    const missing = referenced.filter((src) => !onDisk.has(src))
    expect(missing).toEqual([])
  })

  it('pairs a peak frame with every start frame', () => {
    const paired = generatedExercises.filter((e) => e.image?.endsWith('-start.webp'))
    expect(paired.length).toBeGreaterThan(0)
    for (const exercise of paired) {
      const frames = exercisePhotoFrames(exercise)
      expect(frames, exercise.id).not.toBeNull()
      expect(onDisk, frames!.end).toContain(frames!.end)
    }
  })

  it('only details movements that are in the catalogue', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    const orphans = Object.keys(details).filter((id) => !ids.has(id))
    expect(orphans).toEqual([])
  })

  it('gives every detail record at least one language, and RepDB rows a usable MET', () => {
    type Record_ = { sources: string[]; instructions: Record<string, string[]>; met?: number; nameEs?: string }
    for (const [id, detail] of Object.entries(details as Record<string, Record_>)) {
      expect(detail.sources.length, id).toBeGreaterThan(0)
      const languages = Object.values(detail.instructions).filter((steps) => steps.length > 0)
      expect(languages.length, id).toBeGreaterThan(0)
      if (!detail.sources.includes('repdb')) continue
      expect(detail.nameEs, id).toBeTruthy()
      expect(detail.met, id).toBeGreaterThan(1)
      expect(detail.met, id).toBeLessThan(20)
    }
  })

  it('keeps wger out of the catalogue and credits every row of it', () => {
    /* The whole point of the separate file: share-alike must not reach the
       movements RepDB's licence forbids us to let anyone redistribute. */
    const catalogue = new Set(generatedExercises.map((e) => e.id))
    for (const exercise of wgerExercises) {
      expect(catalogue.has(exercise.id), exercise.id).toBe(false)
      expect(exercise.id.startsWith('wger-'), exercise.id).toBe(true)
      expect(exercise.licenseAuthor, exercise.id).toBeTruthy()
      expect(exercise.license, exercise.id).toMatch(/^CC/)
      expect(exercise.licenseUrl, exercise.id).toMatch(/^https:\/\//)
    }
  })

  it('only carries wger text for wger movements', () => {
    const ids = new Set(wgerExercises.map((e) => e.id))
    const orphans = Object.keys(wgerText).filter((id) => !ids.has(id))
    expect(orphans).toEqual([])
  })

  it('promises no wger language it does not have', () => {
    const text = wgerText as Record<string, Record<string, string[]>>
    for (const exercise of wgerExercises) {
      for (const language of exercise.languages) {
        expect(text[exercise.id]?.[language]?.length, `${exercise.id} ${language}`).toBeGreaterThan(0)
      }
    }
  })

  it('leaves no markup in the wger descriptions', () => {
    /* They arrive as HTML from a public wiki. Flattened at import so nothing
       has to be sanitised at render time. */
    for (const [id, languages] of Object.entries(wgerText as Record<string, Record<string, string[]>>)) {
      for (const steps of Object.values(languages)) {
        for (const step of steps) expect(step, id).not.toMatch(/<[a-z/][^>]*>/i)
      }
    }
  })

  it('points every video at a movement in the catalogue', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    for (const [exerciseId, videoId] of Object.entries(videos as Record<string, string>)) {
      expect(ids, exerciseId).toContain(exerciseId)
      /* A YouTube id is exactly eleven URL-safe characters. Anything else is a
         pasted full URL, which the player would silently fail to load. */
      expect(videoId, exerciseId).toMatch(/^[A-Za-z0-9_-]{11}$/)
    }
  })
})
