import { describe, expect, it } from 'vitest'
import { generatedExercises } from './exercises-generated'
import details from './exercise-details-generated.json'
import illustrations from './images-generated.json'
import { exercisePhotoFrames } from '../lib/images'

/** What is actually on disk, resolved by Vite rather than by reading the filesystem. */
const onDisk = new Set(
  Object.keys(import.meta.glob('../../public/repdb/*.webp')).map((p) => `/repdb/${p.split('/').pop()}`),
)

/**
 * The catalogue is generated by `scripts/import-exercises.mjs` from two
 * upstream datasets that move independently of us. These are the invariants a
 * re-import must not break — most of all the ids, which are written into every
 * logged workout and cannot be renamed without losing somebody's history.
 */
describe('generated exercise catalogue', () => {
  it('has no duplicate ids', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    expect(ids.size).toBe(generatedExercises.length)
  })

  it('keeps the free-exercise-db ids the plan generator hardcodes', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    for (const id of ['Barbell_Bench_Press_-_Medium_Grip', 'Barbell_Full_Squat', 'Pullups', 'Plank']) {
      expect(ids, id).toContain(id)
    }
  })

  it('carries both sources', () => {
    const photos = generatedExercises.filter((e) => e.image?.includes('free-exercise-db'))
    const illustrated = generatedExercises.filter((e) => e.image?.startsWith('/repdb/'))
    expect(photos.length).toBeGreaterThan(800)
    expect(illustrated.length).toBeGreaterThan(400)
  })

  it('classifies every movement', () => {
    expect(generatedExercises.filter((e) => !e.category)).toHaveLength(0)
  })

  it('ships every bundled illustration it points at', () => {
    const referenced = [
      ...generatedExercises.map((e) => e.image),
      ...Object.values(illustrations as Record<string, string>),
    ].filter((src): src is string => !!src && src.startsWith('/repdb/'))
    const missing = referenced.filter((src) => !onDisk.has(src))
    expect(missing).toEqual([])
  })

  it('pairs a peak frame with every start frame', () => {
    const paired = generatedExercises.filter((e) => e.image?.endsWith('-start.webp'))
    expect(paired.length).toBeGreaterThan(0)
    for (const exercise of paired) {
      const frames = exercisePhotoFrames(exercise)
      expect(frames, exercise.id).not.toBeNull()
      expect(onDisk, frames!.end).toContain(frames!.end)
    }
  })

  it('only details movements that are in the catalogue', () => {
    const ids = new Set(generatedExercises.map((e) => e.id))
    const orphans = Object.keys(details).filter((id) => !ids.has(id))
    expect(orphans).toEqual([])
  })

  it('gives every detailed movement Spanish text and a usable MET', () => {
    for (const [id, detail] of Object.entries(details as Record<string, { nameEs: string; instructionsEs: string[]; met: number }>)) {
      expect(detail.nameEs, id).toBeTruthy()
      expect(detail.instructionsEs.length, id).toBeGreaterThan(0)
      expect(detail.met, id).toBeGreaterThan(1)
      expect(detail.met, id).toBeLessThan(20)
    }
  })
})
